
GET http://127.0.0.1:3000 HTTP/1.1

###

POST http://127.0.0.1:3000/user/create HTTP/1.1
Content-Type: application/json

{
    "userId":1,
    "userName":"이재훈"
}

###
GET http://127.0.0.1:3000/user/list HTTP/1.1
###
